---
- name: Login to IaaS
  ovirt_auth:
    url: https://iaas.ull.es/ovirt-engine/api
    insecure: yes
    username: alu0100887037@ULL
    password: Machado1996
    headers:
      filter: true
  debugger: never
